FROM node:lts-alpine

# make the 'app' folder the current working directory
WORKDIR /app

# Install node-gyp dependencies
RUN apk add --no-cache python3 make g++

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# install project dependencies and build app for production with minification
RUN npm install --quiet && npm run build

